### ISSUE TITLE
API does not support PostgreSQL 14

### ISSUE THREAD

**Issue by noliveleger** [sebastianwebber/pgconfig-api#13]
Hello @sebastianwebber,

First of all thank you for your API. It's great. 
I'm using your API with your docker image to fetch the API locally. I need to make it work with PostgreSQL 14 (like https://www.pgconfig.org/) but the code and the image at dockerhub is rather old. Any plans to update them to your latest version?

**Comment by sebastianwebber** [comment]
hey @noliveleger ,

new code, with proper support to pg 14 (and soon 15) is in the new repo: https://github.com/pgconfig/api

**Comment by noliveleger** [comment]
Saw that. Thank you ;-)
